name: flutterproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/apartamento.jpg
    - assets/images/atico.jpg
    - assets/images/casa_del_centro.jpg
    - assets/images/casa_residencial.jpg
    - assets/images/empleo_servicios.jpg
    - assets/images/foto-login-avion-NovaCasa.jpg
    - assets/images/piso_moderno.jpg
    - assets/images/tramites.jpg
    - assets/images/villa_con_jardin.jpg
    - assets/images/vivienda_servicios.jpg