version: '3.8'

services:
  db:
    image: postgres:16
    container_name: novacasa_db
    restart: always
    environment:
      POSTGRES_USER: casanova
      POSTGRES_PASSWORD: estocolmo_rubias
      POSTGRES_DB: novacasadb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: novacasa_backend
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://casanova:estocolmo_rubias@db:5432/novacasadb?schema=public

  frontend:
    build:
      context: ./frontend
    container_name: novacasa_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db_data: